[package]
name = "getrate"
version = "0.1.0"
authors = ["Denis Kolodin <deniskolodin@gmail.com>"]
edition = "2018"

[dependencies]
rillrate = "0.23.1"
env_logger = "0.8.3"
proc = { path = "../proc" }
docker = { path = "../docker" }